server:
  port: 8080
  compression:
    enabled: true

spring:
  application:
    name: book-explorer
  web:
    resources:
      static-locations: classpath:/static/

  groq:
    api-key: gsk_Y74HVh2ewULSL54CDWR2WGdyb3FYB9MbG2wiumVk7WNHRAg3wt0Ce0d94
    model: openai/gpt-oss-120b

logging:
  level:
    com.bookexplorer: INFO
    org.springframework.web.reactive: WARN
